name: Pipeline DEPLOY

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{secrets.AWS_DEFAULT_REGION}}

jobs:
  terraform:
    name: "Criando Infra AWS VPC-ECS-IAM-RDS-ALB"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./env/prod

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Test configuration of AWS CLI
        run: |
          aws --version
          aws configure list | grep region | awk '{print $2}'

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false